### ISSUE TITLE
SC2 screen message during training

### ISSUE THREAD

**Issue by FadyaAbbas** [mzho7212/LICA#5]
Hi, 
Can you please let me know how to get rid of or delete the message (CHEAT local player KillUnitTagBy..) that appears on the game screen during the training?
With many thanks
![SC2 message](https://user-images.githubusercontent.com/79666658/109339142-70b50780-7824-11eb-94a5-a5728f3e9daa.JPG)

**Comment by mzho7212** [comment]
Hi, 

Thank you for your interest. So these messages are actually from the SMAC environment https://github.com/oxwhirl/smac/blob/013cf27001024b4ce47f9506f2541eca0b247c95/smac/env/starcraft2/starcraft2.py#L1357 . As there is no config parameter directly controlling it in pymarl framework, the easiest way to get rid of it is probably manually removing those lines from your local smac repo. 

Hope this helps
