### ISSUE TITLE
about environment

### ISSUE THREAD

**Issue by xu-dong-yuan** [mzho7212/LICA#7]
Excuse me, do you have code for multi particle environment?

**Comment by mzho7212** [comment]
Hi 

Thanks for your interest in our work.

Currently, we do not have plans to prepare a public release for the particle experiments

However, please note that our implementation just follows the official SQDDPG (https://github.com/hsvgbkhgbv/SQDDPG) repo template. To further help you, we’ll share some code pointers on where to add the code from LICA’s SMAC repo:

- Add a file for LICA in `models` directory and follow other existing methods in the template;

- Implement adaptive entropy regularization in the `action_compute_grad()` function in `utilities/trainer.py`;

- Set hyperparameters in `args` directory (create a new file).

For hyperparameters, please have a look at our Appendix A1.2 (available in https://arxiv.org/pdf/2007.02529.pdf, page 14)

For consistency with the baselines provided in the SQDDPG template, we basically follow most training/environment hyperparameters provided there.

Hope this helps.
